"""Init from scratch

Revision ID: 6826d3c888e5
Revises: 
Create Date: 2026-07-09 21:10:24.122107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6826d3c888e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_operaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('jurisdiccion', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_operaciones_id'), 'catalogo_operaciones', ['id'], unique=False)
    op.create_index(op.f('ix_catalogo_operaciones_jurisdiccion'), 'catalogo_operaciones', ['jurisdiccion'], unique=False)
    op.create_index(op.f('ix_catalogo_operaciones_nombre'), 'catalogo_operaciones', ['nombre'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_nombre'), 'workspaces', ['nombre'], unique=False)
    op.create_table('categorias_financieras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_default', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icono', sa.String(length=30), nullable=True),
    sa.Column('es_sistema', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_financieras_id'), 'categorias_financieras', ['id'], unique=False)
    op.create_index(op.f('ix_categorias_financieras_workspace_id'), 'categorias_financieras', ['workspace_id'], unique=False)
    op.create_table('cheques_fojas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('numero_desde', sa.Integer(), nullable=False),
    sa.Column('numero_hasta', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_compra', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cheques_fojas_id'), 'cheques_fojas', ['id'], unique=False)
    op.create_index(op.f('ix_cheques_fojas_numero_desde'), 'cheques_fojas', ['numero_desde'], unique=False)
    op.create_index(op.f('ix_cheques_fojas_workspace_id'), 'cheques_fojas', ['workspace_id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('nacionalidad', sa.String(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('lugar_nacimiento', sa.String(length=150), nullable=True),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('emision_documento', sa.Date(), nullable=True),
    sa.Column('tramite_nro_documento', sa.String(length=50), nullable=True),
    sa.Column('ejemplar_documento', sa.String(length=10), nullable=True),
    sa.Column('vencimiento_documento', sa.Date(), nullable=True),
    sa.Column('exhibio_documento_idoneo', sa.Boolean(), nullable=False),
    sa.Column('tipo_documento_impositivo', sa.String(length=20), nullable=True),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('condicion_iva', sa.String(length=50), nullable=True),
    sa.Column('inscripto_ganancias', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('emails_adicionales', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('telefonos_adicionales', sa.Text(), nullable=True),
    sa.Column('pagina_web', sa.String(length=255), nullable=True),
    sa.Column('domicilio_calle', sa.String(length=255), nullable=True),
    sa.Column('domicilio_numero', sa.String(length=20), nullable=True),
    sa.Column('domicilio_piso', sa.String(length=20), nullable=True),
    sa.Column('domicilio_depto', sa.String(length=20), nullable=True),
    sa.Column('domicilio_cp', sa.String(length=20), nullable=True),
    sa.Column('domicilio_localidad', sa.String(length=100), nullable=True),
    sa.Column('domicilio_provincia', sa.String(length=100), nullable=True),
    sa.Column('domicilio_pais', sa.String(length=100), nullable=True),
    sa.Column('domicilio_fiscal_diferente', sa.Boolean(), nullable=False),
    sa.Column('domicilio', sa.String(length=255), nullable=True),
    sa.Column('nombre_padre', sa.String(length=150), nullable=True),
    sa.Column('apellido_padre', sa.String(length=150), nullable=True),
    sa.Column('nombre_madre', sa.String(length=150), nullable=True),
    sa.Column('apellido_madre', sa.String(length=150), nullable=True),
    sa.Column('estado_familia', sa.String(length=50), nullable=True),
    sa.Column('union_convivencial', sa.Boolean(), nullable=False),
    sa.Column('onboarding_token', sa.String(length=100), nullable=True),
    sa.Column('tipo_persona', sa.String(length=20), nullable=False),
    sa.Column('es_pep', sa.Boolean(), nullable=False),
    sa.Column('riesgo_uif', sa.String(length=50), nullable=False),
    sa.Column('uif_observaciones', sa.Text(), nullable=True),
    sa.Column('uif_estado', sa.String(length=50), nullable=False),
    sa.Column('uif_ultima_revision', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cuit'), 'clientes', ['cuit'], unique=False)
    op.create_index(op.f('ix_clientes_dni'), 'clientes', ['dni'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nombre_completo'), 'clientes', ['nombre_completo'], unique=False)
    op.create_index(op.f('ix_clientes_onboarding_token'), 'clientes', ['onboarding_token'], unique=True)
    op.create_table('configuracion_aranceles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=150), nullable=False),
    sa.Column('tipo_calculo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('minimo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('aplica_a', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_aranceles_id'), 'configuracion_aranceles', ['id'], unique=False)
    op.create_index(op.f('ix_configuracion_aranceles_workspace_id'), 'configuracion_aranceles', ['workspace_id'], unique=False)
    op.create_table('equipo_miembros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipo_miembros_id'), 'equipo_miembros', ['id'], unique=False)
    op.create_table('memoria_notarial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('preferencia', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memoria_notarial_id'), 'memoria_notarial', ['id'], unique=False)
    op.create_index(op.f('ix_memoria_notarial_workspace_id'), 'memoria_notarial', ['workspace_id'], unique=False)
    op.create_table('plantillas_modelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('es_favorito', sa.Boolean(), nullable=False),
    sa.Column('uso_count', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantillas_modelos_id'), 'plantillas_modelos', ['id'], unique=False)
    op.create_index(op.f('ix_plantillas_modelos_nombre'), 'plantillas_modelos', ['nombre'], unique=False)
    op.create_index(op.f('ix_plantillas_modelos_workspace_id'), 'plantillas_modelos', ['workspace_id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('domicilio', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_cuit'), 'proveedores', ['cuit'], unique=False)
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_index(op.f('ix_proveedores_nombre_completo'), 'proveedores', ['nombre_completo'], unique=False)
    op.create_index(op.f('ix_proveedores_workspace_id'), 'proveedores', ['workspace_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('nro_matricula', sa.String(length=50), nullable=True),
    sa.Column('escribania_nombre', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('visibilidad', sa.String(length=10), nullable=False),
    sa.Column('fijada', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['equipo_miembros.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_id'), 'notas', ['id'], unique=False)
    op.create_index(op.f('ix_notas_workspace_id'), 'notas', ['workspace_id'], unique=False)
    op.create_table('tramites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('asignado_a_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('metadata_extra', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asignado_a_id'], ['equipo_miembros.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tramites_id'), 'tramites', ['id'], unique=False)
    op.create_index(op.f('ix_tramites_nombre'), 'tramites', ['nombre'], unique=False)
    op.create_table('documentos_libreria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tramite_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('thread_id_langgraph', sa.String(length=100), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.Column('locked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tramite_id'], ['tramites.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_libreria_id'), 'documentos_libreria', ['id'], unique=False)
    op.create_table('eventos_agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('todo_el_dia', sa.Boolean(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tramite_id', sa.Integer(), nullable=True),
    sa.Column('asignado_a_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.Column('recordatorio_enviado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asignado_a_id'], ['equipo_miembros.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tramite_id'], ['tramites.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_agenda_fecha_inicio'), 'eventos_agenda', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_eventos_agenda_id'), 'eventos_agenda', ['id'], unique=False)
    op.create_index(op.f('ix_eventos_agenda_workspace_id'), 'eventos_agenda', ['workspace_id'], unique=False)
    op.create_table('fojas_usadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('chequera_id', sa.Integer(), nullable=False),
    sa.Column('numero_foja', sa.Integer(), nullable=False),
    sa.Column('tramite_id', sa.Integer(), nullable=True),
    sa.Column('tipo_acto', sa.String(length=150), nullable=False),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('fecha_uso', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chequera_id'], ['cheques_fojas.id'], ),
    sa.ForeignKeyConstraint(['tramite_id'], ['tramites.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fojas_usadas_fecha_uso'), 'fojas_usadas', ['fecha_uso'], unique=False)
    op.create_index(op.f('ix_fojas_usadas_id'), 'fojas_usadas', ['id'], unique=False)
    op.create_index(op.f('ix_fojas_usadas_numero_foja'), 'fojas_usadas', ['numero_foja'], unique=False)
    op.create_index(op.f('ix_fojas_usadas_workspace_id'), 'fojas_usadas', ['workspace_id'], unique=False)
    op.create_table('libro_requerimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('tramite_id', sa.Integer(), nullable=True),
    sa.Column('fecha_asiento', sa.DateTime(), nullable=False),
    sa.Column('nro_correlativo', sa.Integer(), nullable=False),
    sa.Column('tipo_acto', sa.String(length=100), nullable=False),
    sa.Column('intervinientes', sa.Text(), nullable=False),
    sa.Column('fojas', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tramite_id'], ['tramites.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libro_requerimientos_fecha_asiento'), 'libro_requerimientos', ['fecha_asiento'], unique=False)
    op.create_index(op.f('ix_libro_requerimientos_id'), 'libro_requerimientos', ['id'], unique=False)
    op.create_index(op.f('ix_libro_requerimientos_nro_correlativo'), 'libro_requerimientos', ['nro_correlativo'], unique=False)
    op.create_index(op.f('ix_libro_requerimientos_workspace_id'), 'libro_requerimientos', ['workspace_id'], unique=False)
    op.create_table('movimientos_financieros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('tramite_id', sa.Integer(), nullable=True),
    sa.Column('comprobante_tipo', sa.String(length=20), nullable=True),
    sa.Column('comprobante_nro', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_financieras.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['tramite_id'], ['tramites.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_financieros_fecha'), 'movimientos_financieros', ['fecha'], unique=False)
    op.create_index(op.f('ix_movimientos_financieros_id'), 'movimientos_financieros', ['id'], unique=False)
    op.create_index(op.f('ix_movimientos_financieros_tipo'), 'movimientos_financieros', ['tipo'], unique=False)
    op.create_index(op.f('ix_movimientos_financieros_workspace_id'), 'movimientos_financieros', ['workspace_id'], unique=False)
    op.create_table('participaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tramite_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tramite_id'], ['tramites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participaciones_id'), 'participaciones', ['id'], unique=False)
    op.create_table('presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tramite_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('tipo_acto', sa.String(length=100), nullable=False),
    sa.Column('monto_operacion', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tramite_id'], ['tramites.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuestos_id'), 'presupuestos', ['id'], unique=False)
    op.create_index(op.f('ix_presupuestos_workspace_id'), 'presupuestos', ['workspace_id'], unique=False)
    op.create_table('tramite_operaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tramite_id', sa.Integer(), nullable=False),
    sa.Column('catalogo_operacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalogo_operacion_id'], ['catalogo_operaciones.id'], ),
    sa.ForeignKeyConstraint(['tramite_id'], ['tramites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tramite_operaciones_catalogo_operacion_id'), 'tramite_operaciones', ['catalogo_operacion_id'], unique=False)
    op.create_index(op.f('ix_tramite_operaciones_id'), 'tramite_operaciones', ['id'], unique=False)
    op.create_index(op.f('ix_tramite_operaciones_tramite_id'), 'tramite_operaciones', ['tramite_id'], unique=False)
    op.create_table('mensajes_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('tramite_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('modo', sa.String(length=20), server_default='creador', nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_libreria.id'], ),
    sa.ForeignKeyConstraint(['tramite_id'], ['tramites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_chat_cliente_id'), 'mensajes_chat', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_mensajes_chat_documento_id'), 'mensajes_chat', ['documento_id'], unique=False)
    op.create_index(op.f('ix_mensajes_chat_id'), 'mensajes_chat', ['id'], unique=False)
    op.create_index(op.f('ix_mensajes_chat_tramite_id'), 'mensajes_chat', ['tramite_id'], unique=False)
    op.create_table('presupuesto_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('es_porcentaje', sa.Boolean(), nullable=False),
    sa.Column('porcentaje_valor', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuesto_items_id'), 'presupuesto_items', ['id'], unique=False)
    op.create_index(op.f('ix_presupuesto_items_presupuesto_id'), 'presupuesto_items', ['presupuesto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presupuesto_items_presupuesto_id'), table_name='presupuesto_items')
    op.drop_index(op.f('ix_presupuesto_items_id'), table_name='presupuesto_items')
    op.drop_table('presupuesto_items')
    op.drop_index(op.f('ix_mensajes_chat_tramite_id'), table_name='mensajes_chat')
    op.drop_index(op.f('ix_mensajes_chat_id'), table_name='mensajes_chat')
    op.drop_index(op.f('ix_mensajes_chat_documento_id'), table_name='mensajes_chat')
    op.drop_index(op.f('ix_mensajes_chat_cliente_id'), table_name='mensajes_chat')
    op.drop_table('mensajes_chat')
    op.drop_index(op.f('ix_tramite_operaciones_tramite_id'), table_name='tramite_operaciones')
    op.drop_index(op.f('ix_tramite_operaciones_id'), table_name='tramite_operaciones')
    op.drop_index(op.f('ix_tramite_operaciones_catalogo_operacion_id'), table_name='tramite_operaciones')
    op.drop_table('tramite_operaciones')
    op.drop_index(op.f('ix_presupuestos_workspace_id'), table_name='presupuestos')
    op.drop_index(op.f('ix_presupuestos_id'), table_name='presupuestos')
    op.drop_table('presupuestos')
    op.drop_index(op.f('ix_participaciones_id'), table_name='participaciones')
    op.drop_table('participaciones')
    op.drop_index(op.f('ix_movimientos_financieros_workspace_id'), table_name='movimientos_financieros')
    op.drop_index(op.f('ix_movimientos_financieros_tipo'), table_name='movimientos_financieros')
    op.drop_index(op.f('ix_movimientos_financieros_id'), table_name='movimientos_financieros')
    op.drop_index(op.f('ix_movimientos_financieros_fecha'), table_name='movimientos_financieros')
    op.drop_table('movimientos_financieros')
    op.drop_index(op.f('ix_libro_requerimientos_workspace_id'), table_name='libro_requerimientos')
    op.drop_index(op.f('ix_libro_requerimientos_nro_correlativo'), table_name='libro_requerimientos')
    op.drop_index(op.f('ix_libro_requerimientos_id'), table_name='libro_requerimientos')
    op.drop_index(op.f('ix_libro_requerimientos_fecha_asiento'), table_name='libro_requerimientos')
    op.drop_table('libro_requerimientos')
    op.drop_index(op.f('ix_fojas_usadas_workspace_id'), table_name='fojas_usadas')
    op.drop_index(op.f('ix_fojas_usadas_numero_foja'), table_name='fojas_usadas')
    op.drop_index(op.f('ix_fojas_usadas_id'), table_name='fojas_usadas')
    op.drop_index(op.f('ix_fojas_usadas_fecha_uso'), table_name='fojas_usadas')
    op.drop_table('fojas_usadas')
    op.drop_index(op.f('ix_eventos_agenda_workspace_id'), table_name='eventos_agenda')
    op.drop_index(op.f('ix_eventos_agenda_id'), table_name='eventos_agenda')
    op.drop_index(op.f('ix_eventos_agenda_fecha_inicio'), table_name='eventos_agenda')
    op.drop_table('eventos_agenda')
    op.drop_index(op.f('ix_documentos_libreria_id'), table_name='documentos_libreria')
    op.drop_table('documentos_libreria')
    op.drop_index(op.f('ix_tramites_nombre'), table_name='tramites')
    op.drop_index(op.f('ix_tramites_id'), table_name='tramites')
    op.drop_table('tramites')
    op.drop_index(op.f('ix_notas_workspace_id'), table_name='notas')
    op.drop_index(op.f('ix_notas_id'), table_name='notas')
    op.drop_table('notas')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_proveedores_workspace_id'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_nombre_completo'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_cuit'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_plantillas_modelos_workspace_id'), table_name='plantillas_modelos')
    op.drop_index(op.f('ix_plantillas_modelos_nombre'), table_name='plantillas_modelos')
    op.drop_index(op.f('ix_plantillas_modelos_id'), table_name='plantillas_modelos')
    op.drop_table('plantillas_modelos')
    op.drop_index(op.f('ix_memoria_notarial_workspace_id'), table_name='memoria_notarial')
    op.drop_index(op.f('ix_memoria_notarial_id'), table_name='memoria_notarial')
    op.drop_table('memoria_notarial')
    op.drop_index(op.f('ix_equipo_miembros_id'), table_name='equipo_miembros')
    op.drop_table('equipo_miembros')
    op.drop_index(op.f('ix_configuracion_aranceles_workspace_id'), table_name='configuracion_aranceles')
    op.drop_index(op.f('ix_configuracion_aranceles_id'), table_name='configuracion_aranceles')
    op.drop_table('configuracion_aranceles')
    op.drop_index(op.f('ix_clientes_onboarding_token'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nombre_completo'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_dni'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cuit'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_cheques_fojas_workspace_id'), table_name='cheques_fojas')
    op.drop_index(op.f('ix_cheques_fojas_numero_desde'), table_name='cheques_fojas')
    op.drop_index(op.f('ix_cheques_fojas_id'), table_name='cheques_fojas')
    op.drop_table('cheques_fojas')
    op.drop_index(op.f('ix_categorias_financieras_workspace_id'), table_name='categorias_financieras')
    op.drop_index(op.f('ix_categorias_financieras_id'), table_name='categorias_financieras')
    op.drop_table('categorias_financieras')
    op.drop_index(op.f('ix_workspaces_nombre'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_catalogo_operaciones_nombre'), table_name='catalogo_operaciones')
    op.drop_index(op.f('ix_catalogo_operaciones_jurisdiccion'), table_name='catalogo_operaciones')
    op.drop_index(op.f('ix_catalogo_operaciones_id'), table_name='catalogo_operaciones')
    op.drop_table('catalogo_operaciones')
    # ### end Alembic commands ###
